### ISSUE TITLE
nesting if statements

### ISSUE THREAD

**Issue by trbshyguy1010** [azizbecha/shibhouse#25]
not a huge dealbreaker, but maybe you should use `switch` statement instead of nesting `if` conditions as seen here
![Screenshot_2022-11-03-22-33-12-252_com facebook katana](https://user-images.githubusercontent.com/84151427/199840630-133465fc-3789-4d63-a89f-52af9c4ce8d3.jpg)

nice project going on there btw :)

**Comment by azizbecha** [comment]
Hello,
I used nested if statements because those tests should be passed in a specific order, and each exception has its own error message. I hope you get the idea, and thanks for your feedback.
